/**
 * Created by drune on 14/05/2017.
 */

export const START_LIVE_EXCHANGE_RATES = 'START_LIVE_EXCHANGE_RATES'
export const STOP_LIVE_EXCHANGE_RATES = 'STOP_LIVE_EXCHANGE_RATES'
export const EXCHANGE_RATES = 'EXCHANGE_RATES'