/**
 * Created by drune on 14/05/2017.
 */

export const START_LIVE_EXCHANGE_RATES = 'START_LIVE_EXCHANGE_RATES'
export const STOP_LIVE_EXCHANGE_RATES = 'STOP_LIVE_EXCHANGE_RATES'
export const EXCHANGE_RATES = 'EXCHANGE_RATES'
export const SELECT_FROM_ACCOUNT = 'SELECT_FROM_ACCOUNT'
export const SELECT_TO_ACCOUNT = 'SELECT_TO_ACCOUNT'
export const ACCOUNTS_CHANGED = 'ACCOUNTS_CHANGED'
export const AMOUNT_CHANGED = 'AMOUNT_CHANGED'